<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>test</groupId>
    <artifactId>ecommerce-system</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <!--build sub module-->

    <packaging>pom</packaging>
    <name>ecommerce-system</name>
    <description>ecommerce-system</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <modules>
        <module>common</module>
        <module>common/common-starter</module>
        <module>common/common-domain</module>
        <module>common/common-restapi</module>
        <module>order-service</module>
    </modules>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>25</java.version>
        <maven-compile-plugin.version>3.15.0</maven-compile-plugin.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>test</groupId>
                <artifactId>common-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>test</groupId>
                <artifactId>common-restapi</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>test</groupId>
                <artifactId>order-domain-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>test</groupId>
                <artifactId>order-application-service</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>test</groupId>
                <artifactId>order-service-messaging</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>test</groupId>
                <artifactId>order-service-persistence</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>test</groupId>
                <artifactId>order-service-restapi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>test</groupId>
                <artifactId>order-service-main</artifactId>
                <version>${project.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>
    <dependencies>
        <!--  our dependency-->
        <!-- lombok-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
                <!-- lombok-->

                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
