#payment service running port (order-service uses 8550)
server:
  port: 8551
spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ecommerce_user
    password: ecommerce_pass
    url: jdbc:postgresql://localhost:8432/db_payment
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true