<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>test</groupId>
        <artifactId>order-service</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>order-service-main</artifactId>

    <dependencies>
        <dependency>
            <groupId>test</groupId>
            <artifactId>order-application-service</artifactId>
        </dependency>
        <dependency>
            <groupId>test</groupId>
            <artifactId>order-service-messagin</artifactId>
        </dependency>
        <dependency>
            <groupId>test</groupId>
            <artifactId>order-service-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>test</groupId>
            <artifactId>order-service-restapi</artifactId>
        </dependency>
        <dependency>
            <groupId>test</groupId>
            <artifactId>order-domain-core</artifactId>
        </dependency>

        <!--        spring web-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!--        //postgres-->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
</project>