#change order service running port
server:
  port: 8550
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ecommerce_user
    password: ecommerce_pass
    url: jdbc:postgresql://localhost:8432/db_order
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true